LOCATION         = "<<scim_Location>>"
NAME             = "<<scim_Name>>"
TF_SUB_ID        = "<<scim_SUB_ID>>"
TF_CLIENT_ID     = "<<scim_CLIENT_ID>>"
TF_CLIENT_SECRET = "<<scim_CLIENT_SECRET>>"
TF_TENANT_ID     = "<<scim_TENANT_ID>>"
COSMOS_RU           = "1000"
