name: NodeJS CI

on:
  push:
    branches:
      - main
      - bugs/47-fix-gh-action

    paths:
      - 'src/**'
      - '.github/**'

    tags:
      - v*

  pull_request:
    types: [ opened, reopened, synchronize, closed ]
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm packages
      run: |
        # Weirdly it has to be an ordered install: graph-wrapper --> signin --> app
        rm  {graph-wrapper,signin,app}/package-lock.json
        for i in {graph-wrapper,signin,app}; do c="npm install $i --prefix $i";echo "CMD: $c";$c ;done
    - name: Run lint on 'graph-wrapper/'
      run: npm run lint --prefix ./graph-wrapper
    - name: Run Lint on 'signin/'
      run: npm run lint --prefix ./signin
    - name: Run Lint on 'app/'
      run : npm run lint --prefix ./app
    - name: Run tests in 'signin/'
      run: npm run test --prefix ./signin
    # - name: Run tests in 'graph-wrapper/'
    #   run: npm run test --prefix ./graph-wrapper
    # - name: Run tests in 'app/'
    #   run: npm run test --prefix ./app
