name: Docker CI

on:
  push:
    branches:
      - master
      - feature/47-kushal-gh-action

    paths:
      - 'src/**'

    tags:
      - v*

  pull_request:
    types: [ opened, reopened, synchronize, closed ]
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Required global npm Packages
      run: |
        npm install -g eslint eslint-config-airbnb eslint-plugin-standard \
            eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise \
    - name: Install App Specific npm Packages
      run: npm install app/
    - name: Run Linting
      run: npm run lint --prefix ./app
    - name: Run Tests
      run: npm test --prefix ./app
      env:
        CI: true
